#### Social_Network_Ads ML Exercise

1) Read the dataset 'Social_Network_Ads.csv'<br>
2) Remove/handle null values<br>
3) Considering 'Age' and 'Estimated Salary' as input features and 'Purchased' as output feature, generate the following models after splitting the dataset into training and test dataset with test_size as 25%.<br>
a) Logistic Regression <br>
b) Decision Tree <br>
c) RandomForest <br>
d) KNN<br>
and predict the Purchased class label.<br>
4) Generate confusion matrix and classification report for each of these models.<br> 
5) Compute Accuracy score for each of these models.<br>
6) Scale(StandardScaler) the input features using feature Scaling and then repeat question 3, 4 and 5<br>

In [1]:
# Import depenencies
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# 1. Read the dataset 'Social_Network_Ads.csv'
df = pd.read_csv("Datasets/Social_Network_Ads.csv")
df.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB


In [4]:
# 2. Remove/handle null values
df.isna().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [5]:
# 3) Considering 'Age' and 'Estimated Salary' as input features and 'Purchased' as output feature, generate the following
# models after splitting the dataset into training and test dataset with test_size as 25%.
from sklearn.model_selection import train_test_split
X = df.drop(["User ID","Gender","Purchased"],axis=1)
y = df.Purchased
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((300, 2), (100, 2), (300,), (100,))

In [6]:
# a) Logistic Regression b) Decision Tree c) RandomForest d) KNN and predict the Purchased class label.
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
model_preds = {}
models = {"Logistic Regression": LogisticRegression(),
          "Decision Trees": DecisionTreeClassifier(),
          "Random Forest": RandomForestClassifier(),
          "KNN": KNeighborsClassifier()}
for name, model in models.items():
    model.fit(X_train,y_train)
    model_preds[name] = model.predict(X_test)
    score = model.score(X_test,y_test)
    print(f"{name} Score: {round(score*100,2)}%")

Logistic Regression Score: 61.0%
Decision Trees Score: 86.0%
Random Forest Score: 87.0%
KNN Score: 78.0%


In [7]:
# Making a dataframe to store model predictions
preds = pd.DataFrame(model_preds)
preds.head()

Logistic Regression  Decision Trees  Random Forest  KNN
0                    0               1              1    1
1                    0               1              1    0
2                    0               1              1    1
3                    0               0              0    0
4                    0               0              0    0

In [8]:
# 4. Generate confusion matrix and classification report for each of these models.
from sklearn.metrics import confusion_matrix, classification_report
conf_mat_lr = confusion_matrix(y_test,model_preds["Logistic Regression"])
conf_mat_dt = confusion_matrix(y_test,model_preds["Decision Trees"])
conf_mat_rf = confusion_matrix(y_test,model_preds["Random Forest"])
conf_mat_knn = confusion_matrix(y_test,model_preds["KNN"])

print(f"For Logistic Regression:\n{conf_mat_lr}")
print(classification_report(y_test,model_preds["Logistic Regression"]))
print(f"\nFor Decision Trees:\n{conf_mat_dt}")
print(classification_report(y_test,model_preds["Decision Trees"]))
print(f"\nFor Random Forest:\n{conf_mat_rf}")
print(classification_report(y_test,model_preds["Random Forest"]))
print(f"\nFor KNN:\n{conf_mat_knn}")
print(classification_report(y_test,model_preds["KNN"]))

For Logistic Regression:
[[61  0]
 [39  0]]
              precision    recall  f1-score   support

           0       0.61      1.00      0.76        61
           1       0.00      0.00      0.00        39

    accuracy                           0.61       100
   macro avg       0.30      0.50      0.38       100
weighted avg       0.37      0.61      0.46       100


For Decision Trees:
[[54  7]
 [ 7 32]]
              precision    recall  f1-score   support

           0       0.89      0.89      0.89        61
           1       0.82      0.82      0.82        39

    accuracy                           0.86       100
   macro avg       0.85      0.85      0.85       100
weighted avg       0.86      0.86      0.86       100


For Random Forest:
[[54  7]
 [ 6 33]]
              precision    recall  f1-score   support

           0       0.90      0.89      0.89        61
           1       0.82      0.85      0.84        39

    accuracy                           0.87       100
   ma

C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Hp\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [9]:
# 6. Scale(StandardScaler) the input features using feature Scaling and then repeat question 3, 4 and 5
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [10]:
# Refit a) Logistic Regression b) Decision Tree c) RandomForest d) KNN and predict the Purchased class label.
model_preds_2 = {}
models_2 = {"Logistic Regression": LogisticRegression(),
          "Decision Trees": DecisionTreeClassifier(),
          "Random Forest": RandomForestClassifier(),
          "KNN": KNeighborsClassifier()}
for name, model in models_2.items():
    model.fit(X_train,y_train)
    model_preds_2[name] = model.predict(X_test)
    score = model.score(X_test,y_test)
    print(f"{name} Score: {round(score*100,2)}%")

Logistic Regression Score: 80.0%
Decision Trees Score: 85.0%
Random Forest Score: 87.0%
KNN Score: 88.0%


In [11]:
# Making a dataframe to store model predictions
preds_2 = pd.DataFrame(model_preds_2)
preds_2.head()

Logistic Regression  Decision Trees  Random Forest  KNN
0                    1               1              1    1
1                    0               1              1    1
2                    1               1              1    1
3                    0               0              0    0
4                    0               0              0    1

In [12]:
# Repeating confusion matrix and classification report for each of these models.
conf_mat_lr_2 = confusion_matrix(y_test,model_preds_2["Logistic Regression"])
conf_mat_dt_2 = confusion_matrix(y_test,model_preds_2["Decision Trees"])
conf_mat_rf_2 = confusion_matrix(y_test,model_preds_2["Random Forest"])
conf_mat_knn_2 = confusion_matrix(y_test,model_preds_2["KNN"])

print(f"For Logistic Regression:\n{conf_mat_lr_2}")
print(classification_report(y_test,model_preds_2["Logistic Regression"]))
print(f"\nFor Decision Trees:\n{conf_mat_dt_2}")
print(classification_report(y_test,model_preds_2["Decision Trees"]))
print(f"\nFor Random Forest:\n{conf_mat_rf_2}")
print(classification_report(y_test,model_preds_2["Random Forest"]))
print(f"\nFor KNN:\n{conf_mat_knn_2}")
print(classification_report(y_test,model_preds_2["KNN"]))

For Logistic Regression:
[[55  6]
 [14 25]]
              precision    recall  f1-score   support

           0       0.80      0.90      0.85        61
           1       0.81      0.64      0.71        39

    accuracy                           0.80       100
   macro avg       0.80      0.77      0.78       100
weighted avg       0.80      0.80      0.79       100


For Decision Trees:
[[54  7]
 [ 8 31]]
              precision    recall  f1-score   support

           0       0.87      0.89      0.88        61
           1       0.82      0.79      0.81        39

    accuracy                           0.85       100
   macro avg       0.84      0.84      0.84       100
weighted avg       0.85      0.85      0.85       100


For Random Forest:
[[54  7]
 [ 6 33]]
              precision    recall  f1-score   support

           0       0.90      0.89      0.89        61
           1       0.82      0.85      0.84        39

    accuracy                           0.87       100
   ma